<a href="https://colab.research.google.com/github/laxmibansal346/Number-game/blob/main/Copy_of_Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name: LAXMI BANSAL

Roll No.:BETN1AI25226


In [2]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


NumPy Version: 2.0.2


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [25]:
# Create required arrays here

# 1D array of 10 integers
import numpy as np

arr = np.array([2,3,4,5,6,78,9,21,45,78])
print('1D Array:', arr)

# 2D array (3x3 matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('2D Array (3x3)\n:', arr_2d)

# Identity matrix of size 4
identity_matrix = np.identity(4)
print('Identity Matrix (4x4):', identity_matrix)

# Random 5x5 matrix
random_matrix = np.random.rand(5, 5)
print('Random Matrix (5x5):', random_matrix)

1D Array: [ 2  3  4  5  6 78  9 21 45 78]
2D Array (3x3)
: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Identity Matrix (4x4): [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random Matrix (5x5): [[0.58820065 0.96153312 0.60180142 0.58517835 0.58530422]
 [0.45357566 0.79987412 0.72722151 0.20515502 0.41921909]
 [0.09556383 0.57753228 0.10772545 0.968455   0.87771404]
 [0.54078412 0.0029177  0.94967078 0.23259292 0.58786981]
 [0.10172857 0.1087766  0.48430877 0.00574545 0.27805388]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [12]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print(A)
# Extract 2nd row
second_row = A[1]
print('\n')
print("2nd Row:",second_row)
#print(second_row)

# Extract 3rd column
third_column = A[:, 2]
print("\n3rd Column:",third_column)
#print(third_column)

# Extract 2x2 center submatrix
center_submatrix = A[1:3, 1:3]
print("\n2x2 Center Submatrix:",center_submatrix)
#print(center_submatrix)

# Reverse last row
reverse_last_row = A[4][::-1]
print("\nReversed Last Row:",reverse_last_row)
#print(reverse_last_row)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


2nd Row: [ 6  7  8  9 10]

3rd Column: [ 3  8 13 18 23]

2x2 Center Submatrix: [[ 7  8]
 [12 13]]

Reversed Last Row: [25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [23]:
# Perform broadcasting operations here

# Add scalar 10 to matrix

# Add vector [1,2,3,4,5] to each row

# Normalize matrix between 0 and 1
import numpy as np
print("matrix A=",A)
print('\n')
A = np.arange(1, 26).reshape(5,5)

# Add scalar 10 to matrix A
add_scalar = A + 10
print("A + 10:")
print(add_scalar)

# Add vector [1,2,3,4,5] to each row
vector = np.array([1,2,3,4,5])
add_vector = A + vector
print("\nAdd vector to each row:")
print(add_vector)

# Normalize matrix values between 0–1




matrix A= [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


A + 10:
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]

Add vector to each row:
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [15]:

import numpy as np

X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication
element_mul = X * Y
print("Element-wise Multiplication:")
print(element_mul)

# Dot product
dot_product = np.dot(X, Y)
print("\nDot Product:")
print(dot_product)

# Mean
mean_X = np.mean(X)
print("\nMean of X:")
print(mean_X)

# Standard Deviation
std_X = np.std(X)
print("\nStandard Deviation of X:")
print(std_X)

Element-wise Multiplication:
[ 5 12 21 32]

Dot Product:
70

Mean of X:
2.5

Standard Deviation of X:
1.118033988749895


Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [ ]:
marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
# Compute totals, averages, topper